

PUT http://localhost:8080/foundUpdate/6079ff0067205a2d14eacca9
Content-Type: application/json


{
"name": "Air pods Pro",
  "image": "gs://lostandfound-ce0a0.appspot.com/airpods.jpg",
  "brand": "Apple",
  "category": "Mobile Accesories",
  "description": "Found Apple Airpods near David Suzuki School"
}
